/*
 Angel Shah
August 12,2018
ICS4UE
Mr.Jeg
Employee Records Application- user can add employee info such as id, ffirst&last name, annual salary, and start date and store the info on an obbject arraylist.
The user can further add and remove emloyee records from the arraylist and click list to see the currrent employee records
 */
package u2a6_employeerecords;

/**
 *
 * @author angel
 */
import java.util.*;// import for arraylists
public class EmployeeRecords_AShah extends javax.swing.JFrame {
   ArrayList <employees> records= new ArrayList <employees>();// global object arraylist is declared
    
    /**
     * Creates new form EmployeeRecords_AShah
     */
    public EmployeeRecords_AShah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAnnualSalary = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        txtField_IDinput = new javax.swing.JTextField();
        txtField_LastNameInput = new javax.swing.JTextField();
        txtField_FirstNameInput = new javax.swing.JTextField();
        txtField_AnnSalaryInput = new javax.swing.JTextField();
        txtField_StrDate = new javax.swing.JTextField();
        lblRemoveMessage = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_Display = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 255));
        lblTitle.setText("Employee Records");

        lblID.setText("ID # :");

        lblFirstName.setText("First Name :");

        lblLastName.setText("Last Name :");

        lblAnnualSalary.setText("Annual Salary :");

        lblStartDate.setText("Start Date :");

        txtField_IDinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_IDinputActionPerformed(evt);
            }
        });

        txtField_LastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_LastNameInputActionPerformed(evt);
            }
        });

        txtField_FirstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_FirstNameInputActionPerformed(evt);
            }
        });

        txtField_AnnSalaryInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_AnnSalaryInputActionPerformed(evt);
            }
        });

        txtField_StrDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_StrDateActionPerformed(evt);
            }
        });

        lblRemoveMessage.setText("<html>Enter an ID # and press Remove<br> to delete an employee's records. </html>");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        txtArea_Display.setColumns(20);
        txtArea_Display.setRows(5);
        jScrollPane1.setViewportView(txtArea_Display);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartDate)
                    .addComponent(lblLastName)
                    .addComponent(lblAnnualSalary)
                    .addComponent(lblFirstName)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField_StrDate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_AnnSalaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 281, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField_LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemoveMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRemove)
                                            .addComponent(btnAdd))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnList)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnExit)
                                        .addGap(44, 44, 44))))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtField_IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtField_FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtField_LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnnualSalary)
                            .addComponent(txtField_AnnSalaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStartDate)
                            .addComponent(txtField_StrDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblRemoveMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnList)
                            .addComponent(btnExit))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtField_IDinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_IDinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_IDinputActionPerformed

    private void txtField_LastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_LastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_LastNameInputActionPerformed

    private void txtField_FirstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_FirstNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_FirstNameInputActionPerformed

    private void txtField_AnnSalaryInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_AnnSalaryInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_AnnSalaryInputActionPerformed

    private void txtField_StrDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_StrDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_StrDateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     
        employees a;// employee object initialized
        
        String id, firstName, lastName,annualSalary, startDate;// string variables initialized
        id = txtField_IDinput.getText();// takes user input for id and assigns it to String variable id
        firstName= txtField_FirstNameInput.getText();// takes user input for first name and assigns it to String variable firstName
        lastName= txtField_LastNameInput.getText();// takes user input for last name and assigns it to String variable lastName
        annualSalary= txtField_AnnSalaryInput.getText();// takes user input for  annual slary and assigns it to String variable annualSalary
        startDate= txtField_StrDate.getText();// takes user input for their start date and assigns it to String variable startDate
        
        a= new employees(id, firstName, lastName,annualSalary, startDate );// parameters of the object are passed to the object arraylist employees
        records.add(a);// object is added ot the object arraylist
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
       
      
        
        String  idRemove = txtField_IDinput.getText();// takes string input of what id the user wnats to remove
         
      
         for ( int x=0; x<=records.size()-1; x++){// for loop iterates over all indexes of objects in arraylist
             String idAtIndex= records.get(x).id;// the value of the id parameter at the current index in the loop is temporairly stored in the string var idAtIndex
          if (idAtIndex.equals(idRemove)){// if-statements checks to see which index it is that the id the user wnats to remove is at
             records.remove(x);// if that index is found, the entire object( the employee record) is removed from the arraylist
         }
         }        
        
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        
        txtArea_Display.setText("");// sets text area blank so no repetition of text occurs
        
        String temp="";// temporary string variable initialized and set to blank
        for ( int i=0; i<=records.size()-1; i++){// iterates over all indicies of the arraylist 
            temp+=  "\nID #: "+records.get(i).id // the specific info of each employee in the arraylist is printed by haveing that value added to the straing temp variable which gets updated each time the loop iterates
                    +"\nName: "+ records.get(i).firstName+" "+records.get(i).lastName
                    +"\nAnnual Salary: $"+ records.get(i).annualSalary
                    + "\nStart date: "+records.get(i).startDate
                    +"\n--------------------------------";
        }
        
        txtArea_Display.append(temp+"\n");// displays the updated temp string to the text area 
           
    }//GEN-LAST:event_btnListActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        
        System.exit(0);// exits the program and closes the jframe window when the exit button is clicked
        
    }//GEN-LAST:event_btnExitActionPerformed

    class employees{// class for the employee object created
        
        String id, firstName, lastName,annualSalary, startDate;// string variables initialized
        
        //sets up the new object with field names and values when called as a new object.
        employees( String _id, String _firstName, String _lastName, String _annSalary, String _strDate){
            
            id= _id;
            firstName= _firstName;
            lastName= _lastName;
            annualSalary= _annSalary;
            startDate= _strDate;
            
        }
        
    
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords_AShah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords_AShah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords_AShah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords_AShah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRecords_AShah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnnualSalary;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblRemoveMessage;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtArea_Display;
    private javax.swing.JTextField txtField_AnnSalaryInput;
    private javax.swing.JTextField txtField_FirstNameInput;
    private javax.swing.JTextField txtField_IDinput;
    private javax.swing.JTextField txtField_LastNameInput;
    private javax.swing.JTextField txtField_StrDate;
    // End of variables declaration//GEN-END:variables
}
